name: Publish i18n on firebase remote config

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Config Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Publish i18n on firebase remote config
      run: pnpm start
