name: Publish i18n on firebase remote config

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Instalar pnpm
      run: npm install -g pnpm

    - name: Executar pnpm start
      run: pnpm start
